#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

find_champsim_root() {
    local dir="$1"
    while [ "$dir" != "/" ]; do
        if [ -f "$dir/Makefile" ] && [ -d "$dir/src" ] && [ -d "$dir/launch_sim" ]; then
            echo "$dir"
            return 0
        fi
        dir=$(dirname "$dir")
    done
    return 1
}

CHAMPSIM_ROOT=$(find_champsim_root "$SCRIPT_DIR") || {
    echo "[ERROR] Cannot locate ChampSim root from $SCRIPT_DIR"
    exit 1
}

compare_tag_from_dir() {
    local dir="$1"
    local name parent grandparent
    name=$(basename "$dir")
    parent=$(basename "$(dirname "$dir")")
    grandparent=$(basename "$(dirname "$(dirname "$dir")")")
    if [ "$parent" = "spec0617_gapligra-infinite_stlb_prefsweep_fill" ]; then
        echo "${parent}/${name}"
    elif [ "$grandparent" = "spec0617_gapligra-infinite_stlb_prefsweep_fill" ]; then
        echo "${grandparent}/${parent}"
    else
        echo "$parent"
    fi
}

COMPARE_TAG=${COMPARE_TAG:-$(compare_tag_from_dir "$SCRIPT_DIR")}
CONFIG_TAG=$(basename "$SCRIPT_DIR")
BUILD_INFO_FILE="${SCRIPT_DIR}/build_info.env"
CONFIG_FILE="${SCRIPT_DIR}/1C.fullBW.stlb.stats.json"

NUM_CORE=1

DEFAULT_N_WARM=20
DEFAULT_N_SIM=50
DEFAULT_OPTION="--hide-heartbeat"
DEFAULT_TRACE="600.perlbench_s-210B.champsimtrace.xz"
TRACE_DIRS="${TRACE_DIRS:-/data0/tzh/champsim_traces/SPEC06:/data0/tzh/champsim_traces/SPEC17:/data0/tzh/champsim_traces/GAP:/data0/tzh/champsim_traces/Ligra:/data0/tzh/champsim_traces/QMM:/data0/tzh/champsim_traces/PARSEC}"
INFINITE_STLB_SETS=${INFINITE_STLB_SETS:-262144}
INFINITE_STLB_WAYS=${INFINITE_STLB_WAYS:-16}

BINARY_NAME="tlb-infinite-stlb-berti-ip_stride-${NUM_CORE}core"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "[ERROR] Cannot find config file: $CONFIG_FILE"
    exit 1
fi

python3 - "$CONFIG_FILE" "$BINARY_NAME" "$NUM_CORE" <<'PY'
import json
import os
import sys
import tempfile

config_file, binary_name, num_core = sys.argv[1:]
with open(config_file, encoding="utf-8") as rfp:
    config = json.load(rfp)
config["executable_name"] = binary_name
config["num_cores"] = int(num_core)
stlb = config.setdefault("STLB", {})
stlb["sets"] = int(os.environ.get("INFINITE_STLB_SETS", "262144"))
stlb["ways"] = int(os.environ.get("INFINITE_STLB_WAYS", "16"))
directory = os.path.dirname(config_file)
fd, tmp_name = tempfile.mkstemp(prefix=".config_default.", suffix=".json", dir=directory, text=True)
with os.fdopen(fd, "w", encoding="utf-8") as wfp:
    json.dump(config, wfp, indent=2)
    wfp.write("\n")
os.replace(tmp_name, config_file)
PY
chmod 644 "$CONFIG_FILE"

cd "$CHAMPSIM_ROOT"
echo "[CMD] ./config.sh $CONFIG_FILE"
./config.sh "$CONFIG_FILE"
echo "[CMD] make"
make

if [ ! -x "bin/${BINARY_NAME}" ]; then
    echo "ChampSim build FAILED!"
    exit 1
fi

cat > "$BUILD_INFO_FILE" <<EOF
# Auto-generated by build_champsim.sh
COMPARE_TAG="${COMPARE_TAG}"
CONFIG_TAG="${CONFIG_TAG}"
BINARY_NAME="${BINARY_NAME}"
NUM_CORE="${NUM_CORE}"
TRACE_DIRS="${TRACE_DIRS}"
INFINITE_STLB_SETS="${INFINITE_STLB_SETS}"
INFINITE_STLB_WAYS="${INFINITE_STLB_WAYS}"
DEFAULT_N_WARM="${DEFAULT_N_WARM}"
DEFAULT_N_SIM="${DEFAULT_N_SIM}"
DEFAULT_OPTION="${DEFAULT_OPTION}"
DEFAULT_TRACE="${DEFAULT_TRACE}"
CONFIG_FILE="${CONFIG_FILE}"
BUILD_TIME="$(date -Iseconds)"
EOF

echo "ChampSim is successfully built"
echo "Binary: bin/${BINARY_NAME}"
echo "Tags: compare=${COMPARE_TAG} config=${CONFIG_TAG}"
