#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

find_champsim_root() {
    local dir="$1"
    while [ "$dir" != "/" ]; do
        if [ -f "$dir/Makefile" ] && [ -d "$dir/bin" ] && [ -d "$dir/src" ] && [ -d "$dir/launch_sim" ]; then
            echo "$dir"
            return 0
        fi
        dir=$(dirname "$dir")
    done
    return 1
}

CHAMPSIM_ROOT=$(find_champsim_root "$SCRIPT_DIR") || {
    echo "[ERROR] Cannot locate ChampSim root from $SCRIPT_DIR"
    exit 1
}

COMPARE_TAG=$(basename "$(dirname "$SCRIPT_DIR")")
CONFIG_TAG=$(basename "$SCRIPT_DIR")
BUILD_INFO_FILE="${SCRIPT_DIR}/build_info.env"
CONFIG_FILE="${SCRIPT_DIR}/config_default.json"

BRANCH=perceptron
BTB=basic_btb
L1D_PREFETCHER=next_line
L2C_PREFETCHER=sms
LLC_PREFETCHER=no
LLC_REPLACEMENT=lru
NUM_CORE=1

DEFAULT_N_WARM=50
DEFAULT_N_SIM=200
DEFAULT_OPTION="--hide-heartbeat"
DEFAULT_TRACE="600.perlbench_s-210B.champsimtrace.xz"
TRACE_DIR="${TRACE_DIR:-/data0/tzh/champsim_traces/SPEC17}"
WEIGHT_DIR="${WEIGHT_DIR:-${CHAMPSIM_ROOT}/simpoint_weight}"

SMS_DEGREE=4
SMS_REGION_SIZE=2048
SMS_REGION_SIZE_LOG=11
BINARY_BASE="${BRANCH}-${L1D_PREFETCHER}-${L2C_PREFETCHER}-${LLC_PREFETCHER}-${LLC_REPLACEMENT}-${NUM_CORE}core"
BINARY_NAME="${BINARY_BASE}-select_trace_compare-${COMPARE_TAG}-${CONFIG_TAG}-deg${SMS_DEGREE}-r${SMS_REGION_SIZE_LOG}-json"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "[ERROR] Cannot find config file: $CONFIG_FILE"
    exit 1
fi

for pref in "$L1D_PREFETCHER" "$L2C_PREFETCHER" "$LLC_PREFETCHER"; do
    if [ ! -d "${CHAMPSIM_ROOT}/prefetcher/${pref}" ]; then
        echo "[ERROR] Cannot find prefetcher: $pref"
        exit 1
    fi
done
if [ ! -d "${CHAMPSIM_ROOT}/replacement/${LLC_REPLACEMENT}" ]; then
    echo "[ERROR] Cannot find LLC replacement policy: $LLC_REPLACEMENT"
    exit 1
fi

python3 - "$CONFIG_FILE" "$BINARY_NAME" "$NUM_CORE" "$BRANCH" "$BTB" "$L1D_PREFETCHER" "$L2C_PREFETCHER" "$LLC_PREFETCHER" "$LLC_REPLACEMENT" <<'PY'
import json
import os
import sys
import tempfile

config_file, binary_name, num_core, branch, btb, l1d_pref, l2c_pref, llc_pref, llc_repl = sys.argv[1:]
with open(config_file, encoding="utf-8") as rfp:
    config = json.load(rfp)
config["executable_name"] = binary_name
config["num_cores"] = int(num_core)
for cpu in config.get("ooo_cpu", []):
    cpu["branch_predictor"] = branch
    cpu["btb"] = btb
config.setdefault("L1D", {})["prefetcher"] = l1d_pref
config.setdefault("L2C", {})["prefetcher"] = l2c_pref
config.setdefault("LLC", {})["prefetcher"] = llc_pref
config.setdefault("LLC", {})["replacement"] = llc_repl
directory = os.path.dirname(config_file)
fd, tmp_name = tempfile.mkstemp(prefix=".config_default.", suffix=".json", dir=directory, text=True)
with os.fdopen(fd, "w", encoding="utf-8") as wfp:
    json.dump(config, wfp, indent=2)
    wfp.write("\n")
os.replace(tmp_name, config_file)
PY
chmod 644 "$CONFIG_FILE"

cd "$CHAMPSIM_ROOT"
echo "[CMD] ./config.sh $CONFIG_FILE"
./config.sh "$CONFIG_FILE"
echo "[CMD] make"
make

if [ ! -x "bin/${BINARY_NAME}" ]; then
    echo "ChampSim build FAILED!"
    exit 1
fi

cat > "$BUILD_INFO_FILE" <<EOF
# Auto-generated by build_champsim.sh
COMPARE_TAG="${COMPARE_TAG}"
CONFIG_TAG="${CONFIG_TAG}"
BINARY_NAME="${BINARY_NAME}"
BRANCH="${BRANCH}"
BTB="${BTB}"
L1D_PREFETCHER="${L1D_PREFETCHER}"
L2C_PREFETCHER="${L2C_PREFETCHER}"
LLC_PREFETCHER="${LLC_PREFETCHER}"
LLC_REPLACEMENT="${LLC_REPLACEMENT}"
NUM_CORE="${NUM_CORE}"
TRACE_DIR="${TRACE_DIR}"
WEIGHT_DIR="${WEIGHT_DIR}"
DEFAULT_N_WARM="${DEFAULT_N_WARM}"
DEFAULT_N_SIM="${DEFAULT_N_SIM}"
DEFAULT_OPTION="${DEFAULT_OPTION}"
DEFAULT_TRACE="${DEFAULT_TRACE}"
CONFIG_FILE="${CONFIG_FILE}"
SMS_PREF_DEGREE="${SMS_DEGREE}"
SMS_REGION_SIZE="${SMS_REGION_SIZE}"
SMS_REGION_SIZE_LOG="${SMS_REGION_SIZE_LOG}"
BUILD_TIME="$(date -Iseconds)"
EOF

echo "ChampSim is successfully built"
echo "Binary: bin/${BINARY_NAME}"
echo "SMS: region_size=${SMS_REGION_SIZE} region_size_log=${SMS_REGION_SIZE_LOG} pref_degree=${SMS_DEGREE}"
echo "Tags: compare=${COMPARE_TAG} config=${CONFIG_TAG}"
