#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
CHAMPSIM_ROOT=$(cd "${SCRIPT_DIR}/../.." && pwd)
EXP_TAG=$(basename "${SCRIPT_DIR}")
BUILD_INFO_FILE="${SCRIPT_DIR}/build_info.env"
CONFIG_FILE="${SCRIPT_DIR}/config_default.json"

BRANCH=perceptron
BTB=basic_btb
L1D_PREFETCHER=next_line
L2C_PREFETCHER=no
LLC_PREFETCHER=no
LLC_REPLACEMENT=lru
NUM_CORE=1

DEFAULT_N_WARM=50
DEFAULT_N_SIM=200
DEFAULT_OPTION="--hide-heartbeat"
DEFAULT_TRACE="600.perlbench_s-210B.champsimtrace.xz"

NOL2PREF_REGION_SIZE=4096
NOL2PREF_REGION_SIZE_LOG=12

BOLD=$(tput bold || true)
NORMAL=$(tput sgr0 || true)

if [ ! -f "${CONFIG_FILE}" ]; then
    echo "[ERROR] Cannot find config file: ${CONFIG_FILE}"
    exit 1
fi

for pref in "${L1D_PREFETCHER}" "${L2C_PREFETCHER}" "${LLC_PREFETCHER}"; do
    if [ ! -d "${CHAMPSIM_ROOT}/prefetcher/${pref}" ]; then
        echo "[ERROR] Cannot find prefetcher: ${pref}"
        find "${CHAMPSIM_ROOT}/prefetcher" -mindepth 1 -maxdepth 1 -type d -printf "  %f\n" | sort
        exit 1
    fi
done

if [ ! -d "${CHAMPSIM_ROOT}/replacement/${LLC_REPLACEMENT}" ]; then
    echo "[ERROR] Cannot find LLC replacement policy: ${LLC_REPLACEMENT}"
    find "${CHAMPSIM_ROOT}/replacement" -mindepth 1 -maxdepth 1 -type d -printf "  %f\n" | sort
    exit 1
fi

BINARY_BASE="${BRANCH}-${L1D_PREFETCHER}-${L2C_PREFETCHER}-${LLC_PREFETCHER}-${LLC_REPLACEMENT}-${NUM_CORE}core"
BINARY_NAME="${BINARY_BASE}-${EXP_TAG}-r${NOL2PREF_REGION_SIZE_LOG}-json"

python3 - "${CONFIG_FILE}" "${BINARY_NAME}" "${NUM_CORE}" "${BRANCH}" "${BTB}" "${L1D_PREFETCHER}" "${L2C_PREFETCHER}" "${LLC_PREFETCHER}" "${LLC_REPLACEMENT}" <<'PY'
import json
import os
import sys
import tempfile

config_file, binary_name, num_core, branch, btb, l1d_pref, l2c_pref, llc_pref, llc_repl = sys.argv[1:]

with open(config_file, encoding="utf-8") as rfp:
    config = json.load(rfp)

config["executable_name"] = binary_name
config["num_cores"] = int(num_core)

for cpu in config.get("ooo_cpu", []):
    cpu["branch_predictor"] = branch
    cpu["btb"] = btb

config.setdefault("L1D", {})["prefetcher"] = l1d_pref
config.setdefault("L2C", {})["prefetcher"] = l2c_pref
config.setdefault("LLC", {})["prefetcher"] = llc_pref
config.setdefault("LLC", {})["replacement"] = llc_repl

directory = os.path.dirname(config_file)
fd, tmp_name = tempfile.mkstemp(prefix=".config_default.", suffix=".json", dir=directory, text=True)
with os.fdopen(fd, "w", encoding="utf-8") as wfp:
    json.dump(config, wfp, indent=2)
    wfp.write("\n")
os.replace(tmp_name, config_file)
PY

cd "${CHAMPSIM_ROOT}"

echo "[BUILD] no L2 prefetcher base"
echo "[CMD] ./config.sh ${CONFIG_FILE}"
./config.sh "${CONFIG_FILE}"

echo "[CMD] make"
make

if [ ! -x "bin/${BINARY_NAME}" ]; then
    echo "${BOLD}ChampSim build FAILED!${NORMAL}"
    exit 1
fi

cat > "${BUILD_INFO_FILE}" <<EOF
# Auto-generated by build_champsim.sh
EXP_TAG="${EXP_TAG}"
BINARY_NAME="${BINARY_NAME}"
BRANCH="${BRANCH}"
BTB="${BTB}"
L1D_PREFETCHER="${L1D_PREFETCHER}"
L2C_PREFETCHER="${L2C_PREFETCHER}"
LLC_PREFETCHER="${LLC_PREFETCHER}"
LLC_REPLACEMENT="${LLC_REPLACEMENT}"
NUM_CORE="${NUM_CORE}"
DEFAULT_N_WARM="${DEFAULT_N_WARM}"
DEFAULT_N_SIM="${DEFAULT_N_SIM}"
DEFAULT_OPTION="${DEFAULT_OPTION}"
DEFAULT_TRACE="${DEFAULT_TRACE}"
CONFIG_FILE="${CONFIG_FILE}"
NOL2PREF_REGION_SIZE="${NOL2PREF_REGION_SIZE}"
NOL2PREF_REGION_SIZE_LOG="${NOL2PREF_REGION_SIZE_LOG}"
BUILD_TIME="$(date -Iseconds)"
EOF

echo "${BOLD}ChampSim is successfully built${NORMAL}"
echo "Binary: bin/${BINARY_NAME}"
echo "Config: ${CONFIG_FILE}"
echo "No L2 prefetcher base: region_size=${NOL2PREF_REGION_SIZE} region_size_log=${NOL2PREF_REGION_SIZE_LOG}"
echo "Default run args: [BINARY]=${BINARY_NAME} [N_WARM]=${DEFAULT_N_WARM} [N_SIM]=${DEFAULT_N_SIM} [TRACE]=${DEFAULT_TRACE} [OPTION]=${DEFAULT_OPTION}"
